name: Compile PDF using Typst
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Typst
        uses: yusancky/setup-typst@v1
        with:
          version: 'v0.2.0'
      - name: Compile PDF
        run: typst --font-path ./fonts compile cv.typ
      - name: Add PDF to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update PDF
          file_pattern: '*.pdf'
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: cv
          path: cv.pdf
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%d/%m/%Y)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: "*.pdf"
